os: linux
language: node_js
node_js:
  - 10
jobs:
  include:
    - stage: npm release
      script: yarn test
      before_deploy:
        yarn build
      deploy:
        provider: npm
        cleanup: false
        edge: true
        api_token: $NPM_TOKEN
        on:
          branch: release
