os: linux
language: node_js
node_js:
  - 10
script:
  - yarn test
before_deploy:
  - yarn prepare
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: release
