os: linux
language: node_js
node_js:
  - 10
jobs:
  include:
    - stage: npm release
      script: yarn test
      before_deploy:
        yarn build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        cleanup: false
        on:
          branch: release
